version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_DB_URI: $MONGO_DB_URI
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      OWNER_ID: $OWNER_ID
      STRING_SESSION: $STRING_SESSION
      LOG_GROUP_ID: $LOG_GROUP_ID
      UPSTREAM_REPO: $UPSTREAM_REPO
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
